// Import the Task type
import { Task } from '@/app/types';

/**
 * Adds a specified number of days to a date
 */
export function addDays(date: Date, days: number): Date {
  const result = new Date(date);
  result.setDate(result.getDate() + days);
  return result;
} 

/**
 * Groups tasks by their type
 * @param tasks Array of Task objects
 * @returns Dictionary where keys are task types and values are arrays of tasks with that type
 */
export function groupTasksByType(tasks: Task[]): Record<string, Task[]> {
  return tasks.reduce((acc, task) => {
    const typeName = task.type.name;
    if (!acc[typeName]) {
      acc[typeName] = [];
    }
    acc[typeName].push(task);
    return acc;
  }, {} as Record<string, Task[]>);
} 

/**
 * Extracts plain text from an HTML report generated by generateReportHTML
 * @param html The HTML report string
 * @returns A clean, prompt-friendly list of tasks
 */
export function extractPlainTextFromReport(html: string): string {
  // Handle empty HTML report
  if (!html || html.trim() === '') {
    return '';
  }

  // Remove link tags and &nbsp;
  const processed = html
    .replace(/<a href=".*?">#<\/a>/g, '')
    .replace(/&nbsp;/g, ' ');

  // Recursively flatten nested <ul> structures
  function flattenLists(html: string, indent: number): string {
    let result = '';
    const liRegex = /<li>([\s\S]*?)<\/li>/g;
    let match;

    while ((match = liRegex.exec(html)) !== null) {
      const content = match[1];
      const nestedUlMatch = content.match(/<ul>([\s\S]*?)<\/ul>/);
      const prefix = '  '.repeat(indent) + '• ';

      if (nestedUlMatch) {
        // This <li> contains a nested <ul>
        const mainText = content.replace(/<ul>[\s\S]*?<\/ul>/, '').trim();
        if (mainText) {
          result += prefix + mainText + '\n';
        }
        // Recurse into nested <ul>
        result += flattenLists(nestedUlMatch[1], indent + 1);
      } else {
        const text = content.trim();
        if (text) {
          result += prefix + text + '\n';
        }
      }
    }

    return result;
  }

  // Extract <ul> blocks and flatten them
  const ulRegex = /<ul>([\s\S]*?)<\/ul>/g;
  let text = processed;
  text = text.replace(ulRegex, (_, ulContent) => flattenLists(ulContent, 0));

  // Convert headers to newlines
  text = text.replace(/<h[2-3]>(.*?)<\/h[2-3]>/g, '\n$1\n');

  // Clean up remaining tags
  text = text.replace(/<[^>]+>/g, '');

  // Clean up multiple newlines and spaces
  return text
    .split('\n')
    .map(line => line.trim())
    .filter(line => line.length > 0)
    .join('\n');
} 